// const Mdata = [
//   {
//     id: 1,
//     pname: "Chicken Biryani",
//     category: "biryani",
//     price: 369,
//     imgsrc: "./images/biryani-1.jpg",
//   },
//   {
//     id: 2,
//     pname: "Margherita Pizza",
//     category: "pizza",
//     price: 238,
//     imgsrc: "./images/pizza-1.jpg",
//   },
//   {
//     id: 3,
//     pname: "Bun Tikki Burger",
//     category: "burger",
//     price: 98,
//     imgsrc: "./images/burger-1.jpg",
//   },
//   {
//     id: 4,
//     pname: "Veg Biryani",
//     category: "biryani",
//     price: 249,
//     imgsrc: "./images/biryani-2.jpg",
//   },
//   {
//     id: 5,
//     pname: "Vegetable Noodles",
//     category: "noodles",
//     price: 249,
//     imgsrc: "./images/noodles-1.jpg",
//   },
//   {
//     id: 6,
//     pname: "Paneer Tikka Biryani",
//     category: "biryani",
//     price: 299,
//     imgsrc: "./images/biryani-3.jpg",
//   },
//   {
//     id: 7,
//     pname: "Cheese Onion Pizza",
//     category: "pizza",
//     price: 299,
//     imgsrc: "./images/pizza-2.jpg",
//   },
//   {
//     id: 8,
//     pname: "Cheesy Chicken Pizza",
//     category: "pizza",
//     price: 349,
//     imgsrc: "./images/pizza-3.jpg",
//   },
//   {
//     id: 9,
//     pname: "Crispy Chicken Burger",
//     category: "burger",
//     price: 129,
//     imgsrc: "./images/burger-3.jpg",
//   },
//   {
//     id: 10,
//     pname: "Vegetable Singapore Noodles",
//     category: "noodles",
//     price: 385,
//     imgsrc: "./images/noodles-3.jpg",
//   },
//   {
//     id: 11,
//     pname: "BBQ Chicken Burger",
//     category: "burger",
//     price: 189,
//     imgsrc: "./images/burger-2.jpg",
//   },
//   {
//     id: 12,
//     pname: "Chicken Garlic Noodles",
//     category: "noodles",
//     price: 345,
//     imgsrc: "./images/noodles-2.jpg",
//   },
// ];

const Mdata= [
  {
    id: 1,
    pname: "Butter Chicken with Naan",
    category: "meal",
    price: 11.99,
    imgsrc: "./images/butterchicken.jpeg",
  },
  {
    id: 2,
    pname: "Beef Sausage Roll",
    category: "snack",
    price: 2.99,
    imgsrc: "./images/beefroll.jpg",
  },
  {
    id: 3,
    pname: "Chicken Samosa",
    category: "snack",
    price: 2.99,
    imgsrc: "./images/csamosa.jpeg",
  },
  {
    id: 4,
    pname: "Vegetable Samosa",
    category: "snack",
    price: 1.79,
    imgsrc: "./images/ssamosa.jpeg",
  },
  {
    id: 5,
    pname: "Ham & Cheese Sandwich",
    category: "sandwich",
    price: 8.49,
    imgsrc: "./images/ham.jpeg",
  },
  {
    id: 6,
    pname: "Turkey & Cheese Sandwich",
    category: "sandwich",
    price: 9.99,
    imgsrc: "./images/tsandwhich.jpeg",
  },
  {
    id: 7,
    pname: "Chicken Sandwich",
    category: "sandwich",
    price: 8.49,
    imgsrc: "./images/chickensandwich.jpeg",
  },
  {
    id: 8,
    pname: "Bacon Sandwich",
    category: "sandwich",
    price: 8.49,
    imgsrc: "./images/bsand.jpeg",
  },
  {
    id: 9,
    pname: "Rueben Sandwich",
    category: "sandwich",
    price: 8.49,
    imgsrc: "./images/rsand.jpeg",
  },
  {
    id: 10,
    pname: "Corn Beef Sandwich",
    category: "sandwich",
    price: 8.49,
    imgsrc: "./images/cbsand.jpeg",
  },
  {
    id: 11,
    pname: "Roast Beef Sandwich",
    category: "sandwich",
    price: 8.49,
    imgsrc: "./images/rbsand.jpg",
  },
  {
    id: 12,
    pname: "Pizza Salami Sandwich",
    category: "sandwich",
    price: 8.49,
    imgsrc: "./images/pssand.jpeg",
  },
];

export default Mdata;
